apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-disease-api
  labels:
    app: plant-disease-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-disease-api
  template:
    metadata:
      labels:
        app: plant-disease-api
    spec:
      containers:
        - name: plant-disease-api
          image: plant-disease-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"